### ISSUE TITLE
run command format error

### ISSUE THREAD

**Issue by ioshc** [zxbu/webdav-teambition#2]
--teambition.cookies="_ga=xxxxx; sensorsdata2015jssdkcross=xxxxx; TB_STICKY=xxxxxxA%22www.teambition.com%22%2C%22path7D; TB_ACCESS_TOKEN=eyJhbG=; mp_tbpanel__c=0"

之间已省略很多文字

**Comment by zxbu** [comment]
有错误日志吗？ 贴出来

**Comment by zxbu** [comment]
最新的版本支持了账号密码登录方式，你试一下。我先关了issue ，有问题你再打开
