### ISSUE TITLE
无法删除文件/删除的文件自动恢复

### ISSUE THREAD

**Issue by 9N9N7S** [zxbu/webdav-teambition#3]
首先感谢您的项目，我在使用过程中遇到以下问题，当我删除一个文件后过了几秒刷新后那个文件还是存在，关闭程序后删除文件不会恢复，重新开启程序后所删除的文件又重新出现。

**Comment by zxbu** [comment]
你是怎么使用的？ 文件还存在是指在哪个地方还存在？ 是teambition上面吗？ 
如果关闭程序后文件不在，重启后又出现，是不是自动同步上去的？

**Comment by 9N9N7S** [comment]
是的，运行jar文件后，又会自动同步到teambition上无法删除，关闭程序后问题不会出现。

**Comment by zxbu** [comment]
那应该是你所用的自动同步软件，自动同步上去的，检查一下。

**Comment by zxbu** [comment]
我先关闭这个issue，有问题再交流
